//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauThu
    {
        public CauThu()
        {
            this.ThamGias = new HashSet<ThamGia>();
        }
    
        public string MaCT { get; set; }
        public string HoTen { get; set; }
        public string MaDB { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
