//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiBong
    {
        public DoiBong()
        {
            this.CauThus = new HashSet<CauThu>();
            this.TranDaus = new HashSet<TranDau>();
            this.TranDaus1 = new HashSet<TranDau>();
        }
    
        public string MaDB { get; set; }
        public string TenDB { get; set; }
        public string CLB { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual ICollection<CauThu> CauThus { get; set; }
        public virtual ICollection<TranDau> TranDaus { get; set; }
        public virtual ICollection<TranDau> TranDaus1 { get; set; }
    }
}
