////------------------------------------------------------------------------------
//// <auto-generated>
////    This code was generated from a template.
////
////    Manual changes to this file may cause unexpected behavior in your application.
////    Manual changes to this file will be overwritten if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace TestIIS.Models
//{
//    using System;
//    using System.Data.Entity;
//    using System.Data.Entity.Infrastructure;
    
//    public partial class BongDaEntities : DbContext
//    {
//        public BongDaEntities()
//            : base("name=BongDaEntities")
//        {
//        }
    
//        protected override void OnModelCreating(DbModelBuilder modelBuilder)
//        {
//            throw new UnintentionalCodeFirstException();
//        }
    
//        public DbSet<CauThu> CauThus { get; set; }
//        public DbSet<DoiBong> DoiBongs { get; set; }
//        public DbSet<ThamGia> ThamGias { get; set; }
//        public DbSet<TranDau> TranDaus { get; set; }
//    }
//}
