//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiBong_CLB2
    {
        public string MaDB { get; set; }
        public string TenDB { get; set; }
        public string CLB { get; set; }
    }
}
