//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamGia
    {
        public string MaTD { get; set; }
        public string MaCT { get; set; }
        public Nullable<int> SoTrai { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual CauThu CauThu { get; set; }
        public virtual TranDau TranDau { get; set; }
    }
}
