//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestIIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranDau
    {
        public TranDau()
        {
            this.ThamGias = new HashSet<ThamGia>();
        }
    
        public string MaTD { get; set; }
        public string MaDB1 { get; set; }
        public string MaDB2 { get; set; }
        public string TrongTai { get; set; }
        public string SanDau { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual DoiBong DoiBong { get; set; }
        public virtual DoiBong DoiBong1 { get; set; }
        public virtual ICollection<ThamGia> ThamGias { get; set; }
    }
}
